import {DEFAULT_MAP, TOWERS} from '../content/index.ts';
import {canPlace} from '../navigation/index.ts';
import type {BonusChoice, RunModel, Settlement, SpawnBatch, Tower, TowerKind, Vec2} from '../contracts/index.ts';

export type ActionResult={ok:true}|{ok:false;reason:string}; export type PlaceResult=ActionResult&{tower?:Tower};
type Wave={spawns:readonly SpawnBatch[];payment:number;bonus:boolean}; type Applied=Pick<Settlement,'kills'|'crushKills'|'leaks'|'earned'>&{tick:number}; type SavedRun={version:1;model:RunModel;epoch:number;applied:Applied};
const SAVE_KEY='pressure-front.run.v1';
const WAVES:readonly Wave[]=[
 {spawns:[{kind:'shambler',count:150,seed:101}],payment:90,bonus:false},
 {spawns:[{kind:'runner',count:90,seed:201},{kind:'shambler',count:210,seed:202}],payment:120,bonus:true},
 {spawns:[{kind:'brute',count:42,seed:301},{kind:'shambler',count:458,seed:302}],payment:165,bonus:false},
 {spawns:[{kind:'runner',count:370,seed:401},{kind:'brute',count:75,seed:402},{kind:'shambler',count:355,seed:403}],payment:220,bonus:true},
 {spawns:[{kind:'shambler',count:430,seed:501},{kind:'runner',count:220,seed:502},{kind:'brute',count:150,seed:503}],payment:300,bonus:false},
];
const BONUS_CHOICES:readonly BonusChoice[]=[{id:'hydraulic-advantage',name:'Hydraulic Advantage',description:'Repulsors push harder but pulse a little slower.'},{id:'cold-fracture',name:'Cold Fracture',description:'Cryo emitters control a wider area.'},{id:'salvage-contract',name:'Salvage Contract',description:'Gain 35 scrap now.'}];
const emptyApplied=():Applied=>({kills:0,crushKills:0,leaks:0,earned:0,tick:-1});
const copy=(m:RunModel):RunModel=>({...m,towers:m.towers.map(t=>({...t})),pending:m.pending.map(b=>({...b})),bonusChoices:m.bonusChoices.map(b=>({...b})),bonuses:[...m.bonuses]});
const fresh=():RunModel=>({phase:'preparation',scrap:450,baseHealth:20,wave:0,waveCount:WAVES.length,towers:[],selected:null,pending:[],bonusChoices:[],bonuses:[]});

export class RunController {
 readonly model:RunModel=fresh(); private nextTowerId=1; private runEpoch=1; private applied=emptyApplied(); private live=0;
 get epoch():number{return this.runEpoch} get isBossWave():boolean{return this.model.wave===this.model.waveCount}
 place(kind:TowerKind,position:Vec2):PlaceResult { if(this.model.phase!=='preparation')return {ok:false,reason:'Towers can only be placed during preparation.'};const def=TOWERS[kind];if(this.model.scrap<def.cost)return {ok:false,reason:'Insufficient scrap.'};if(!canPlace(DEFAULT_MAP,this.model.towers,position,1.25))return {ok:false,reason:'That position is blocked or too close to another tower.'};const tower:Tower={id:this.nextTowerId++,kind,x:position.x,y:position.y,level:0,branch:-1,angle:0,cooldown:0,spent:def.cost};this.model.scrap-=def.cost;this.model.towers.push(tower);this.model.selected=tower.id;return {ok:true,tower}; }
 sell(id:number):ActionResult {if(this.model.phase!=='preparation')return {ok:false,reason:'Towers can only be sold during preparation.'};const i=this.model.towers.findIndex(t=>t.id===id);if(i<0)return {ok:false,reason:'Tower not found.'};const [tower]=this.model.towers.splice(i,1);this.model.scrap+=Math.floor(tower.spent*.7);if(this.model.selected===id)this.model.selected=null;return {ok:true};}
 upgrade(id:number,branch:number):ActionResult {const tower=this.model.towers.find(t=>t.id===id);if(!tower)return {ok:false,reason:'Tower not found.'};if(branch!==0&&branch!==1)return {ok:false,reason:'Choose branch 0 or 1.'};if(tower.branch>=0&&tower.branch!==branch)return {ok:false,reason:'This tower is committed to its other branch.'};if(tower.level>=3)return {ok:false,reason:'This tower is fully upgraded.'};const cost=45+tower.level*35;if(this.model.scrap<cost)return {ok:false,reason:'Insufficient scrap.'};this.model.scrap-=cost;tower.spent+=cost;tower.level++;tower.branch=branch;return {ok:true};}
 startWave():ActionResult {if(this.model.phase!=='preparation')return {ok:false,reason:'The current wave is not ready to start.'};if(this.model.bonusChoices.length)return {ok:false,reason:'Choose a run bonus first.'};if(this.model.wave>=WAVES.length)return {ok:false,reason:'All waves are complete.'};const wave=WAVES[this.model.wave++];this.model.pending=wave.spawns.map(b=>({...b}));this.model.phase='combat';this.live=0;return {ok:true};}
 takeSpawns(capacity:number):SpawnBatch[] {if(this.model.phase!=='combat'||capacity<=0)return [];let left=Math.floor(capacity);const out:SpawnBatch[]=[];while(left>0&&this.model.pending.length){const batch=this.model.pending[0],count=Math.min(batch.count,left);out.push({...batch,count});left-=count;this.live+=count;if(count===batch.count)this.model.pending.shift();else{batch.count-=count;batch.seed=(batch.seed+count)>>>0;}}return out;}
 applySettlement(s:Settlement):void {if(!Number.isFinite(s.epoch)||!Number.isFinite(s.tick)||s.epoch<this.runEpoch||(s.epoch===this.runEpoch&&s.tick<=this.applied.tick))return;if(s.epoch>this.runEpoch){this.runEpoch=s.epoch;this.applied=emptyApplied();}const delta=(n:keyof Pick<Settlement,'kills'|'crushKills'|'leaks'|'earned'>)=>Math.max(0,s[n]-this.applied[n]);const leaks=delta('leaks'),earned=delta('earned');this.applied={kills:s.kills,crushKills:s.crushKills,leaks:s.leaks,earned:s.earned,tick:s.tick};this.model.scrap+=earned;this.model.baseHealth=Math.max(0,this.model.baseHealth-leaks);this.live=Math.max(0,s.live);if(this.model.baseHealth===0)this.model.phase='lost';}
 finishSettling():ActionResult {if(this.model.phase!=='combat'&&this.model.phase!=='settling')return {ok:false,reason:'There is no wave to settle.'};if(this.model.pending.length||this.live>0){this.model.phase='settling';return {ok:false,reason:'Waiting for live enemies or queued spawns.'};}const completed=WAVES[this.model.wave-1];this.model.scrap+=completed.payment;if(this.model.wave===this.model.waveCount){this.model.phase='won';return {ok:true};}this.model.phase='preparation';this.model.bonusChoices=completed.bonus?BONUS_CHOICES.filter(b=>!this.model.bonuses.includes(b.id)).slice(0,2):[];return {ok:true};}
 chooseBonus(id:string):ActionResult {const bonus=this.model.bonusChoices.find(b=>b.id===id);if(!bonus)return {ok:false,reason:'That bonus is not available.'};this.model.bonuses.push(id);if(id==='salvage-contract')this.model.scrap+=35;this.model.bonusChoices=[];return {ok:true};}
 reset():void {Object.assign(this.model,fresh());this.nextTowerId=1;this.runEpoch++;this.applied=emptyApplied();this.live=0;}
 save():string {if(this.model.phase==='combat'||this.model.phase==='settling')throw new Error('Runs can only be saved between waves.');const text=JSON.stringify({version:1,model:copy(this.model),epoch:this.runEpoch,applied:this.applied} satisfies SavedRun);try{if(typeof window!=='undefined')window.localStorage.setItem(SAVE_KEY,text)}catch{}return text;}
 load(text?:string):ActionResult {try{const raw=text??(typeof window!=='undefined'?window.localStorage.getItem(SAVE_KEY):null);if(!raw)return {ok:false,reason:'No saved run found.'};const saved=JSON.parse(raw) as SavedRun;if(saved.version!==1||!saved.model||saved.model.phase==='combat'||saved.model.phase==='settling'||!Array.isArray(saved.model.towers)||!Number.isFinite(saved.model.scrap)||!Number.isFinite(saved.model.baseHealth))return {ok:false,reason:'Invalid saved run.'};const m=copy(saved.model);Object.assign(this.model,m);this.nextTowerId=Math.max(0,...m.towers.map(t=>t.id))+1;this.runEpoch=Math.max(this.runEpoch+1,Math.floor(saved.epoch)+1);this.applied=emptyApplied();this.live=0;return {ok:true};}catch{return {ok:false,reason:'Invalid saved run.'};}}
}
export const createRun=():RunController=>new RunController();
